"""Generate paper/numbers.tex from data/results.json.

Every number that appears in the manuscript comes from here, so there is exactly one path from
the analysis output to the rendered page: results.json -> macro -> main.tex -> PDF.
`crosscheck.py` walks that path and fails if a numeral in the .tex is not backed by a macro.

Usage:  python make_macros.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import bench      # noqa: E402
import models     # noqa: E402

D = bench.ROOT / "data"
OUT = bench.ROOT / "paper" / "numbers.tex"

NAME = {"qwen25": "Qwen", "dscoder": "DsCoder", "mistral": "Mistral",
        "llama3": "Llama", "gemini": "Gemini"}


def pct(x: float, nd: int = 1) -> str:
    return f"{100 * x:.{nd}f}"


def main() -> None:
    r = json.loads((D / "results.json").read_text(encoding="utf-8"))
    ref = json.loads((D / "reference.json").read_text(encoding="utf-8"))
    dropped = json.loads((D / "reference_dropped.json").read_text(encoding="utf-8"))
    probe = json.loads((D / "probe.json").read_text(encoding="utf-8"))
    elig = json.loads((D / "eligible.json").read_text(encoding="utf-8"))

    L: list[str] = [
        "% GENERATED by code/make_macros.py from data/results.json. Do not edit by hand.",
        "% Regenerate after every analysis run; the build is not valid without it.",
    ]

    def add(name: str, val) -> None:
        L.append(f"\\newcommand{{\\{name}}}{{{val}}}")

    # ---- amendment count, read from the frozen spec so the manuscript cannot drift from it
    import re
    spec = (bench.ROOT / "SPEC.md").read_text(encoding="utf-8")
    n_amend = len(re.findall(r"\*\*Amendment\s+(\d+)\s*\|", spec))
    add("NAmendments", n_amend)

    # ---- corpus
    add("NHumanEval", len(probe))
    add("NSigEligible", len(elig))
    add("NProblems", len(ref))
    add("NDropped", len(dropped))
    add("NFuzz", bench.N_FUZZ)
    add("MutantFloor", f"{100 * bench.MUTANT_KILL_FLOOR:.0f}")
    add("KParity", bench.K_PARITY)
    add("NModels", len(models.MODELS))
    add("NCells", r.get("n_cells", 0))

    # ---- translation and divergence prevalence
    prev = r.get("divergence_prevalence", {})
    tot_usable = sum(v["n_usable"] for v in prev.values())
    tot_div = sum(v["n_divergent"] for v in prev.values())
    add("NUsable", tot_usable)
    add("NDivergent", tot_div)
    add("DivRate", pct(tot_div / tot_usable) if tot_usable else "0.0")
    for mid, v in prev.items():
        add(f"Usable{NAME[mid]}", v["n_usable"])
        add(f"Div{NAME[mid]}", pct(v["divergence_rate"]))

    # ---- RQ1
    q1 = r.get("rq1", {})
    add("EscapeRate", pct(q1.get("escape_rate", float("nan"))))
    add("EscapeLo", pct(q1.get("ci", [float("nan")] * 2)[0]))
    add("EscapeHi", pct(q1.get("ci", [float("nan")] * 2)[1]))
    add("NEscaped", q1.get("n_escaped", 0))
    add("NPassed", q1.get("n_passed", 0))

    for mid, v in r.get("rq1_by_validator", {}).items():
        add(f"Escape{NAME[mid]}", pct(v["escape_rate"]))

    q1o = r.get("rq1_ordinary", {})
    if q1o:
        add("EscapeOrdinary", pct(q1o["escape_rate"]))
        add("EscapeOrdinaryLo", pct(q1o["ci"][0]))
        add("EscapeOrdinaryHi", pct(q1o["ci"][1]))
        add("NEscapedOrdinary", q1o.get("n_escaped", 0))
    if "ordinary_share_of_divergences" in r:
        add("OrdinaryShare", pct(r["ordinary_share_of_divergences"]))
    # ground-truth sensitivity for RQ1: escape rate when only the oracle's own witnesses count
    q1x = r.get("rq1_oracle_only", {})
    if q1x:
        add("EscapeOracleOnly", pct(q1x["escape_rate"]))
        add("NEscapedOracleOnly", q1x.get("n_escaped", 0))
    # import-repair disclosure and its robustness bound
    q1r = r.get("rq1_excl_repaired", {})
    if q1r:
        add("NRepairedTranslations", q1r["n_repaired_translations"])
        add("NRepairedLlama", q1r.get("repaired_by_model", {}).get("llama3", 0))
        add("EscapeExclRepaired", pct(q1r["escape_rate"]))
    # escape rate BY TRANSLATOR (residual risk after a pass, per code source)
    for mid, v in r.get("rq1_by_translator", {}).items():
        add(f"EscapeTrans{NAME[mid]}", pct(v["escape_rate"]))

    # ---- RQ2
    q2 = r.get("rq2", {})
    if q2:
        add("SelfMiss", pct(q2["self"]["miss_rate"]))
        add("SelfMissLo", pct(q2["self"]["ci"][0]))
        add("SelfMissHi", pct(q2["self"]["ci"][1]))
        add("SelfMissN", q2["self"]["n"])
        add("CrossMiss", pct(q2["cross"]["miss_rate"]))
        add("CrossMissLo", pct(q2["cross"]["ci"][0]))
        add("CrossMissHi", pct(q2["cross"]["ci"][1]))
        add("CrossMissN", q2["cross"]["n"])
        add("MissDiff", f"{q2['diff_pp']:.1f}")
        if "diff_ci_pp" in q2:
            add("MissDiffLo", f"{q2['diff_ci_pp'][0]:.1f}")
            add("MissDiffHi", f"{q2['diff_ci_pp'][1]:.1f}")
        pm = q2.get("permutation_preregistered", {})
        if pm.get("n_groups"):
            add("PermGroups", pm["n_groups"])
            add("PermSelfMiss", pct(pm["self_miss_rate"]))
            add("PermCrossMiss", pct(pm["cross_miss_rate"]))
            add("PermDiff", f"{pm['diff_pp']:.1f}")
            p = pm["p_value"]
            add("PermP", f"{p:.3f}" if p >= 0.001 else "$<$0.001")
        dx = q2.get("permutation_diagonal_exact", {})
        if dx.get("n_permutations"):
            add("DiagMiss", pct(dx["diagonal_miss_rate"]))
            add("OffDiagMiss", pct(dx["offdiagonal_miss_rate"]))
            add("PseudoDiagMiss", pct(dx["mean_pseudodiagonal"]))
            add("DiagPerms", dx["n_permutations"])
            add("DiagP", f"{dx['p_value_one_sided_diag_worse']:.2f}")
            add("DiagDiff", f"{dx['diagonal_excess_pp']:.1f}")
            add("DiagNullLo", pct(dx["null_range"][0]))
            add("DiagNullHi", pct(dx["null_range"][1]))

    for mid, v in r.get("validator_skill_offdiag", {}).items():
        add(f"VMiss{NAME[mid]}", pct(v["miss_rate"]))
    for mid, v in r.get("translation_subtlety_offdiag", {}).items():
        add(f"THard{NAME[mid]}", pct(v["miss_rate"]))
    tf = r.get("two_factor", {})
    if tf:
        add("BestValidatorMiss", pct(tf["best_validator_miss"]))
        add("HardestTranslatorMiss", pct(tf["hardest_translator_miss"]))
        w = tf.get("worst_cell")
        if w:
            add("WorstCellMiss", pct(w["miss_rate"]))
            add("WorstCellN", w["n"])

    wvs = r.get("within_validator_summary", {})
    if wvs:
        add("WVValidators", wvs["n_validators"])
        add("WVWorseOnOwn", wvs["n_worse_on_own"])
        add("WVMeanDiff", f"{wvs['mean_diff_pp']:.1f}")
    pr_ = r.get("pairing", {})
    if pr_:
        add("PairTranslations", pr_["n_divergent_translations"])
        add("PairAllFive", pr_["n_scored_by_all_validators"])
        add("PairMedian", pr_["median_validators_per_translation"])
    if "target_timeouts" in r:
        add("TargetTimeouts", r["target_timeouts"])
    # Two analyses that answer a question with a number instead of a hedge. Both are computed
    # by their own scripts and read here.
    cp = D / "coverage_escape.json"
    if cp.exists():
        c = json.loads(cp.read_text(encoding="utf-8"))
        add("CovEscapes", c["n_escapes_analysed"])
        add("CovSamePath", pct(c["share_on_already_covered_paths"]))
        add("NTraceFailed", c.get("n_trace_failed", 0))
    cd_ = D / "category_detection.json"
    if cd_.exists():
        c = json.loads(cd_.read_text(encoding="utf-8"))
        g = c.get("by_group", {})
        if "cross_language" in g and "logic" in g:
            add("MissCrossLang", pct(g["cross_language"]["miss_rate"]))
            add("MissLogic", pct(g["logic"]["miss_rate"]))
        bc = c.get("by_category", {})
        if "integer_width" in bc:
            add("MissIntWidth", pct(bc["integer_width"]["miss_rate"]))
            # the cross-language class WITHOUT integer width, so the manuscript can say
            # honestly how much of the class gap that one subcategory carries
            gx = c["by_group"]["cross_language"]
            n_missed = round(gx["n"] * gx["miss_rate"])
            iw_missed = round(bc["integer_width"]["n"] * bc["integer_width"]["miss_rate"])
            n_rest = gx["n"] - bc["integer_width"]["n"]
            add("CrossExIntMiss", pct((n_missed - iw_missed) / max(1, n_rest)))

    tf_ = r.get("translation_funnel", {})
    if tf_:
        add("NAttempted", tf_["attempted"])
        add("NCompiled", tf_["compiled"])
        add("NCompileFail", tf_["compile_failures"])
        add("NNoComparable", tf_["no_comparable_inputs"])

    rp = D / "regression.json"
    if rp.exists():
        rg = json.loads(rp.read_text(encoding="utf-8"))
        fe = rg.get("fixed_effects", {})
        if fe:
            add("RegCells", rg["n_cells"])
            add("RegOR", f"{fe['self_odds_ratio']:.2f}")
            add("RegORLo", f"{fe['ci_odds_ratio'][0]:.2f}")
            add("RegORHi", f"{fe['ci_odds_ratio'][1]:.2f}")
            add("NBootRegression", f"{fe.get('n_boot', 0):,}")
            add("RegP", f"{fe['p_cluster_bootstrap']:.2f}")
        ge = rg.get("gee_logistic", {})
        if ge and "self_odds_ratio" in ge:
            add("GeeOR", f"{ge['self_odds_ratio']:.2f}")
            add("GeeP", f"{ge['self_p']:.2f}")

    ms = r.get("matched_subsample", {})
    if ms:
        add("MatchTrans", ms["n_translations"])
        add("MatchSelfMiss", pct(ms["self"]["miss_rate"]))
        add("MatchCrossMiss", pct(ms["cross"]["miss_rate"]))
        add("MatchSelfN", ms["self"]["n"])
        add("MatchCrossN", ms["cross"]["n"])
        mp = ms.get("permutation_diagonal", {})
        if mp.get("n_permutations"):
            add("MatchP", f"{mp['p_value_one_sided_diag_worse']:.2f}")

    ds = r.get("dropout_symmetry", {})
    if ds.get("self") and ds.get("cross"):
        add("DropSelf", pct(ds["self"]["dropout_rate"]))
        add("DropCross", pct(ds["cross"]["dropout_rate"]))
        if "n_worse_on_self" in ds:
            add("DropWorseSelfN", ds["n_worse_on_self"])
            add("DropValidatorsChecked", ds["n_validators_checked"])
    du = r.get("rq2", {}).get("permutation_diagonal_union", {})
    if du.get("n_permutations"):
        add("DiagPUnion", f"{du['p_value_one_sided_diag_worse']:.2f}")
    tw = r.get("rq1_twoway_ci")
    if tw:
        add("EscapeTwoLo", pct(tw[0]))
        add("EscapeTwoHi", pct(tw[1]))
    jk = r.get("jackknife_escape", {})
    if jk:
        add("JackLo", pct(jk["min"]))
        add("JackHi", pct(jk["max"]))

    c4 = r.get("control_c4", {})
    if c4:
        add("CfourDropped", c4["n_dropped"])
        add("CfourNondet", c4["n_dropped_nondeterministic"])
    c1 = r.get("control_c1", {})
    if c1:
        add("ConeTags", c1["n_type_tags_round_tripped"])
        add("ConeMismatch", c1["n_mismatches"])

    wvu = r.get("within_validator_union_summary", {})
    if wvu:
        add("WVWorseOnOwnUnion", wvu["n_worse_on_own"])
        add("WVMeanDiffUnion", f"{wvu['mean_diff_pp']:.1f}")

    q2e = r.get("rq2_escape", {})
    if q2e:
        add("SelfEscape", pct(q2e["self"]["escape_rate"]))
        add("CrossEscape", pct(q2e["cross"]["escape_rate"]))

    # ---- K sensitivity
    word = {"k3": "KThree", "k5": "KFive", "k10": "KTen"}
    for k, v in r.get("k_sensitivity", {}).items():
        w = word.get(k, k.upper())
        add(f"Escape{w}", pct(v["escape_rate"]))
        add(f"SelfMiss{w}", pct(v["self_miss"]))
        add(f"CrossMiss{w}", pct(v["cross_miss"]))

    # ---- RQ4
    q4 = r.get("rq4_targeted", {})
    if q4 and "n_paired_cells" in q4:
        add("TargetedMiss", pct(q4["miss_rate_targeted"]))
        add("PlainMiss", pct(q4["miss_rate_plain_diag"]))
        add("TargetedGain", f"{abs(q4['miss_rate_reduction_pp']):.1f}")
        add("TargetedPairs", q4["n_paired_cells"])
        add("TargetedOnlyWin", q4["caught_only_targeted"])
        add("TargetedOnlyLoss", q4["caught_only_plain"])
        add("TargetedP", f"{q4['mcnemar_p']:.3f}")  # 3dp: 0.625 is a rounding boundary at 2dp

    # ---- random baseline
    b = r.get("baseline_random", {})
    if b:
        add("RandomEscape", pct(b["escape_rate"]))
        add("RandomCells", b["n_cells"])
    sc = r.get("selector_comparison_loo", {})
    if sc:
        add("RandomMiss", pct(sc["random"]["miss_rate"]))
        add("RandomMissN", sc["random"]["n"])
        add("LlmMissAll", pct(sc["llm"]["miss_rate"]))
        add("LlmMissN", sc["llm"]["n"])
    bv = r.get("selector_comparison_biased_views", {})
    if bv:
        add("RandomMissUnion", pct(bv["union_favours_llm"]["random_miss"]))
        add("LlmMissUnion", pct(bv["union_favours_llm"]["llm_miss"]))
        add("RandomMissOracle", pct(bv["oracle_only_favours_random"]["random_miss"]))
        add("LlmMissOracle", pct(bv["oracle_only_favours_random"]["llm_miss"]))
    cm = r.get("complementarity", {})
    if cm:
        add("ComboMissLlm", pct(cm["miss_rate_llm_only"]))
        add("ComboMissRandom", pct(cm["miss_rate_random_only"]))
        add("ComboMissBoth", pct(cm["miss_rate_combined"]))
        # Derive the difference from the DISPLAYED values, not the unrounded ones, so a reader
        # who subtracts the two printed percentages gets the printed gain. 49.5 - 40.9 is 8.6;
        # the unrounded difference rounds to 8.7, and printing both invites a correct reader to
        # think the paper cannot subtract.
        # Deliberately the difference of the two PRINTED (rounded) operands, not the unrounded
        # gain (8.665 -> 8.7): readers check the subtraction against the two numbers on the
        # page, and a value they cannot reproduce from the printed operands reads as an error.
        add("ComboGain", f"{float(pct(cm['miss_rate_llm_only'])) - float(pct(cm['miss_rate_combined'])):.1f}")
        add("ComboOnlyLlm", cm["caught_only_by_llm"])
        add("ComboOnlyRandom", cm["caught_only_by_random"])
        add("ComboCells", cm["n_cells"])

    os_ = r.get("oracle_supplemented", {})
    if os_:
        add("OnlySuiteFound", os_["n_found_only_by_a_suite"])
        add("DivTransUnion", os_["n_divergent_translations_union"])
        add("DivTransOracle", os_["n_divergent_translations_oracle"])
        add("OnlySuiteShare", pct(os_["share_of_divergent_translations"]))

    # ---- suite health
    sh = r.get("suite_health", {})
    if sh:
        add("NSuites", sh["n_total"])
        add("NUnparseable", sh["n_unparseable"])
        add("NDegenerate", sh["n_degenerate"])
        add("PctUnparseable", pct(sh["n_unparseable"] / max(1, sh["n_total"])))
        if "escape_rate_incl_degenerate" in sh:
            add("EscapeWithDegenerate", pct(sh["escape_rate_incl_degenerate"]))
        add("NCallFailed", sh.get("n_call_failed", 0))

    # ---- per-validator suite health, so the manuscript never types one of these by hand
    for mid, v in (sh.get("by_validator", {}) if sh else {}).items():
        add(f"Degen{NAME[mid]}", v["degenerate"])
        add(f"Unparse{NAME[mid]}", v["unparseable"])

    # ---- the worked escape example (median), extracted from the data rather than transcribed.
    # A named example in prose is still a measurement, and the gate is right to demand a macro.
    op = D / "oracle" / "gemini.json"
    if op.exists():
        for x in json.loads(op.read_text(encoding="utf-8")):
            if x.get("task_id") == "Python/47" and x.get("examples"):
                ex = x["examples"][0]
                add("MedianSrc", ex["py"].get("v"))
                add("MedianTgt", ex["jv"].get("v"))
                add("MedianDiverge", x["n_diverge"])
                add("MedianComparable", x["n_comparable"])
                break

    # ---- model-call constants for the configuration disclosure, read from models.py, the
    # code that made the calls: the paper's stated limits must not be able to drift from them.
    import inspect as _inspect
    add("MaxTokensPerCall", f"{models.MAX_TOKENS:,}")
    add("CallRetries", _inspect.signature(models.call).parameters["retries"].default)

    # ---- generator constants for the operational-rules paragraph. Read from bench.py, the
    # code that ran, never typed: the paper's description of the generator must not be able to
    # drift from the generator.
    add("BoundaryFraction", f"{bench.BOUNDARY_FRACTION:.2f}")
    add("NScalarIntBoundaries", len(bench.SCALAR_INT_BOUNDARIES))
    add("NElemExtraBoundaries", len(bench.ELEM_INT_BOUNDARIES) - len(bench.SCALAR_INT_BOUNDARIES))
    add("NFloatBoundaries", len(bench.FLOAT_BOUNDARIES))
    add("NStrBoundaries", len(bench.STR_BOUNDARIES))
    add("MaxStrBoundaryLen", max(len(s) for s in bench.STR_BOUNDARIES))
    import inspect
    import re as _re
    _gv = inspect.getsource(bench.gen_value)
    _m = _re.search(r"rng\.random\(\) < (0\.\d+)", _gv)
    if _m:
        add("ListShapeProb", _m.group(1))

    # ---- the second worked escape example (greatest_common_divisor), same discipline as the
    # median one: every value in the prose is read from the data, never transcribed.
    op = D / "oracle" / "dscoder.json"
    if op.exists():
        for x in json.loads(op.read_text(encoding="utf-8")):
            if x.get("task_id") == "Python/13" and x.get("examples"):
                ex = x["examples"][0]
                add("GcdInA", ex["in"][0])
                add("GcdInB", ex["in"][1])
                add("GcdSrc", ex["py"].get("v"))
                add("GcdTgt", ex["jv"].get("v"))
                add("GcdDiverge", x["n_diverge"])
                add("GcdComparable", f"{x['n_comparable']:,}")
                break
    # how many validators' plain suites PASSED that divergent translation (what makes it an
    # escape), counted from the parity records rather than asserted in prose
    pdir = D / "parity"
    if pdir.exists():
        n_pass = n_usable = n_caught = 0
        for f in sorted(pdir.glob("*.json")):
            for rr in json.loads(f.read_text(encoding="utf-8")):
                if (rr.get("translator") == "dscoder" and rr.get("task_id") == "Python/13"
                        and rr.get("status") == "ok"):
                    kk = rr.get("full") or {}
                    if kk and not kk.get("degenerate"):
                        n_usable += 1
                        if kk.get("caught"):
                            n_caught += 1
                        else:
                            n_pass += 1
        add("GcdPassedValidators", n_pass)
        add("GcdUsableSuites", n_usable)
        add("GcdCaughtValidators", n_caught)

    # ---- Amendment 10 accounting: how much of the corpus the representability rule removes.
    # Computed here rather than typed, because it is a measurement like any other.
    LIM = 2 ** 63 - 1

    def _out(v):
        if isinstance(v, bool):
            return False
        if isinstance(v, int):
            return abs(v) > LIM
        if isinstance(v, list):
            return any(_out(x) for x in v)
        return False

    n_int = n_out = 0
    probs_out = set()
    for p in ref:
        if "int" not in p["return_type"]:
            continue
        for x in p["source_out"]:
            if not x.get("ok"):
                continue
            n_int += 1
            if _out(x.get("v")):
                n_out += 1
                probs_out.add(p["task_id"])
    add("IntReturning", f"{n_int:,}")
    add("OutOfRange", f"{n_out:,}")
    add("OutOfRangeProblems", len(probs_out))

    # ---- controls
    c2 = r.get("control_c2", {})
    if c2:
        add("CtwoMutants", c2["n_mutants"])
        add("CtwoKill", pct(c2["kill_rate"]))
        add("CtwoBenchKill", pct(c2["benchmark_kill_rate"]))
        # The gap between the two, as a macro rather than a qualitative gloss ("barely more than
        # a point"). A benchmark-input fix once moved this gap from 1.3pp to 6.6pp while the
        # prose describing it stayed a fixed phrase, and no gate traces prose against a macro it
        # does not name; this closes that hole for this specific claim by removing the need for
        # words to track a value at all.
        add("CtwoGapPP", f"{100 * (c2['kill_rate'] - c2['benchmark_kill_rate']):.1f}")
    c3 = r.get("control_c3", {})
    if c3:
        add("CthreeN", c3["n"])
        add("CthreeCaught", c3["n_caught"])
    cs = r.get("control_c3surv", {})
    if cs:
        add("CthreeEquivalent", cs["n_likely_equivalent"])
        add("CthreeGenuineMiss", cs["n_genuine_miss"])
        add("CthreeExtraInputs", f"{cs['extra_inputs_each']:,}".replace(",", ","))
    bs = r.get("benchmark_suite", {})
    if bs:
        add("BenchDetect", pct(bs["detection_rate"]))
        add("BenchDetected", bs["n_detected_by_benchmark_inputs"])
        add("BenchDivergent", bs["n_divergent"])
        add("BenchInputsMean", f"{bs['mean_benchmark_inputs_per_problem']:.0f}")

    c5 = r.get("control_c5", {})
    if c5:
        add("CfiveChecked", c5["n_checked"])
        add("CfiveViolations", c5["n_violations"])

    # ---- taxonomy
    tax = D / "taxonomy.json"
    if tax.exists():
        from collections import Counter
        rows = json.loads(tax.read_text(encoding="utf-8"))
        c = Counter(x["category"] for x in rows)
        tot = sum(c.values())
        add("NClassified", tot)
        g = Counter(x.get("group") for x in rows)
        add("CrossLangShare", pct(g["cross_language"] / max(1, tot)))
        add("LogicShare", pct(g["logic"] / max(1, tot)))
        add("NCrossLang", g["cross_language"])
        gm = {}
        for x in rows:
            gm.setdefault(x["model"], Counter())[x.get("group")] += 1
        for mid, cc in gm.items():
            n = cc["cross_language"] + cc["logic"]
            add(f"CrossLang{NAME[mid]}", pct(cc["cross_language"] / max(1, n)))
        top = c.most_common(3)
        for i, (k, v) in enumerate(top, start=1):
            add(f"TaxName{'One' if i == 1 else 'Two' if i == 2 else 'Three'}",
                k.replace("_", " "))
            add(f"TaxPct{'One' if i == 1 else 'Two' if i == 2 else 'Three'}",
                pct(v / max(1, tot)))
        add("TaxTopThree", pct(sum(v for _k, v in top) / max(1, tot)))

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT} with {len(L) - 2} macros")

    # ---- table bodies, generated so a hand-typed cell cannot drift from the data
    disp = {"qwen25": "Qwen2.5 7B", "dscoder": "DS-Coder 6.7B", "mistral": "Mistral 7B",
            "llama3": "Llama 3 8B", "gemini": "Gemini 3.6 F"}
    T: list[str] = ["% GENERATED by code/make_macros.py. Do not edit by hand."]

    rows = []
    for m in models.MODELS:
        v = prev.get(m.mid)
        if not v:
            continue
        ev = r.get("rq1_by_validator", {}).get(m.mid, {})
        rows.append(
            f"{disp[m.mid]} & {v['n_usable']} & {v['n_divergent']} & "
            f"{100 * v['divergence_rate']:.1f} & "
            f"{100 * ev.get('escape_rate', float('nan')):.1f} \\\\")
    T.append("\\newcommand{\\SummaryBody}{%")
    T.extend(rows)
    T.append("}")

    mat = r.get("matrix_miss_rate", {})
    if mat:
        head = " & ".join(disp[m.mid].split()[0] for m in models.MODELS)
        T.append(f"\\newcommand{{\\MatrixHead}}{{{head}}}")
        mrows = []
        for v in models.MODELS:
            cells = []
            for t in models.MODELS:
                c = mat.get(v.mid, {}).get(t.mid)
                if not c:
                    cells.append("--")
                elif v.mid == t.mid:
                    cells.append(f"\\textbf{{{100 * c['miss_rate']:.0f}}}")
                else:
                    cells.append(f"{100 * c['miss_rate']:.0f}")
            mrows.append(f"{disp[v.mid].split()[0]} & " + " & ".join(cells) + " \\\\")
        T.append("\\newcommand{\\MatrixBody}{%")
        T.extend(mrows)
        T.append("}")

    tax = D / "taxonomy.json"
    if tax.exists():
        from collections import Counter
        trows = json.loads(tax.read_text(encoding="utf-8"))
        c = Counter(x["category"] for x in trows)
        tot = sum(c.values())
        # Show the head, then an EXPLICIT remainder row. A truncated table whose column does not
        # sum to the stated total reads as if it were the whole story; a reader adding the
        # visible rows would get 154 of 165 and nothing would tell them why.
        TOP = 7
        head = c.most_common(TOP)
        lines = [f"{k.replace('_', ' ')} & {v} & {100 * v / max(1, tot):.1f} \\\\"
                 for k, v in head]
        rest_n = tot - sum(v for _k, v in head)
        rest_k = len(c) - len(head)
        if rest_n > 0:
            lines.append("\\midrule")
            lines.append(f"{rest_k} further categories & {rest_n} & "
                         f"{100 * rest_n / max(1, tot):.1f} \\\\")
            lines.append(f"\\textbf{{total}} & \\textbf{{{tot}}} & \\textbf{{100.0}} \\\\")
        T.append("\\newcommand{\\TaxonomyBody}{%")
        T.extend(lines)
        T.append("}")

    tp = bench.ROOT / "paper" / "tables.tex"
    tp.write_text("\n".join(T) + "\n", encoding="utf-8")
    print(f"wrote {tp}")


if __name__ == "__main__":
    main()
